Routing/Areas/WebShop/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Routing.Areas.WebShop.Models
{
    public class Cart
    {
        public List<CartItem> Items { get; set; }
        public decimal TotalPrice { get
            {
                return Items.Sum(x => x.Amount * x.Product.Price);
            }
        }
    }
}

Routing/Areas/WebShop/Models/CartItem.cs
using Routing.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Routing.Areas.WebShop.Models
{
    public class CartItem
    {
        public Product Product { get; set; }
        public int Amount { get; set; }
    }
}

Routing/Models/Product.cs
namespace Routing.Models
{
    public class Product
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
    }
}

Routing/Areas/WebShop/Controllers/CartController.cs
using Routing.Areas.WebShop.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Routing.Areas.WebShop.Controllers
{
    public class CartController : Controller
    {
        public ActionResult Index()
        {
            var products = ProductRepository.GetProducts().ToList();
            var cart = new Cart();

            cart.Items = new List<CartItem>() {
                new CartItem() { Amount = 3, Product = products[0] },
                new CartItem() { Amount = 1, Product = products[2] },
                new CartItem() { Amount = 2, Product = products[3] },
                new CartItem() { Amount = 1, Product = products[5] }
            };

            return View(cart);
        }
    }
}

Routing/Controllers/ProductController.cs
using Routing.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Routing.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index()
        {
            var products = ProductRepository.GetProducts();
            return View(products);
        }

        public ActionResult Detail(int Id)
        {
            var products = ProductRepository.GetProducts();
            var product = products.FirstOrDefault(x => x.Id.Equals(Id));
            return View(product);
        }

        public ActionResult DetailByName(string Name)
        {
            var products = ProductRepository.GetProducts();
            var product = products.FirstOrDefault(x => x.Name.Equals(Name));
            return View("Detail",product);
        }
    }
}

Routing/Areas/WebShop/Views/Cart/Index.cshtml
@model Routing.Areas.WebShop.Models.Cart

@{
    ViewBag.Title = "Index";
}

<h2>Cart</h2>

<ul>
    @foreach (var cartItem in Model.Items)
    {
        <li>@cartItem.Amount x @cartItem.Product.Name</li>
    }
</ul>

<h3>Total Price: € @Model.TotalPrice</h3>

Routing/Views/Product/Detail.cshtml
@model Routing.Models.Product

@{
    ViewBag.Title = "Index";
}

<h2>@Model.Name (€ @Model.Price)</h2>
<h3>@Model.Description</h3>

Routing/Views/Product/Index.cshtml
@model List<Routing.Models.Product>

@{
    ViewBag.Title = "Products";
}

<h2>Products</h2>

<ul>
    @foreach (var product in Model)
    {
        <li>
            @Html.ActionLink(product.Name,"Detail", new { Id = product.Id })
        </li>
    }
</ul>

Routing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Product", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Products", "Index", "Product", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("WebShop", "Index", "Cart", new { area = "WebShop" }, null)</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>